name: clip
description: .
version: 1.1.3
homepage: https://github.com/hsul4n/dart-clip

environment:
  sdk: ">2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  photo_view: ^0.12.0
  image_picker: ^0.8.4
  flutter_cache_manager: ^3.1.2
  flutter_native_image: ^0.0.6+1

dev_dependencies:
  test: ^1.5.1
